/**
 * Unit tests for action link generator (JWT signing/verification).
 * Requirements: 9.1, 9.2
 */
import { describe, it, expect } from 'vitest';
import { generateActionLinks, validateActionToken } from './action-link-generator.js';

const TEST_SECRET = 'test-secret-key-for-unit-tests-minimum-length';
const TEST_BASE_URL = 'https://api.travel-policy.example.com';

const TEST_PAYLOAD = {
  workflowId: 'wf-123-456',
  stageNumber: 1,
  action: 'approve' as const,
  approverId: 'approver-001',
  tenantId: 'tenant-abc',
};

describe('generateActionLinks', () => {
  it('should generate three action links (approve, reject, request_info)', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });

    expect(links).toHaveLength(3);
    expect(links.map((l) => l.action)).toEqual(['approve', 'reject', 'request_info']);
  });

  it('should generate valid URLs with token query parameter', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });

    for (const link of links) {
      expect(link.url).toContain(`${TEST_BASE_URL}/v1/approvals/email-action?token=`);
      expect(link.url).toContain(`&action=${link.action}`);
      expect(link.token).toBeTruthy();
      expect(link.token.split('.')).toHaveLength(3); // JWT has 3 parts
    }
  });

  it('should set expiry to 24 hours by default', async () => {
    const before = Date.now();
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });
    const after = Date.now();

    for (const link of links) {
      const expiresAt = new Date(link.expiresAt).getTime();
      const expectedMin = before + 24 * 60 * 60 * 1000;
      const expectedMax = after + 24 * 60 * 60 * 1000;
      expect(expiresAt).toBeGreaterThanOrEqual(expectedMin - 1000);
      expect(expiresAt).toBeLessThanOrEqual(expectedMax + 1000);
    }
  });

  it('should respect custom expiry hours', async () => {
    const before = Date.now();
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
      expiryHours: 2,
    });
    const after = Date.now();

    for (const link of links) {
      const expiresAt = new Date(link.expiresAt).getTime();
      const expectedMin = before + 2 * 60 * 60 * 1000;
      const expectedMax = after + 2 * 60 * 60 * 1000;
      expect(expiresAt).toBeGreaterThanOrEqual(expectedMin - 1000);
      expect(expiresAt).toBeLessThanOrEqual(expectedMax + 1000);
    }
  });
});

describe('validateActionToken', () => {
  it('should validate a token generated by generateActionLinks', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });

    const approveLink = links.find((l) => l.action === 'approve')!;
    const result = await validateActionToken(approveLink.token, TEST_SECRET);

    expect(result.workflowId).toBe(TEST_PAYLOAD.workflowId);
    expect(result.stageNumber).toBe(TEST_PAYLOAD.stageNumber);
    expect(result.action).toBe('approve');
    expect(result.approverId).toBe(TEST_PAYLOAD.approverId);
    expect(result.tenantId).toBe(TEST_PAYLOAD.tenantId);
    expect(result.expiresAt).toBeTruthy();
  });

  it('should validate reject and request_info tokens', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });

    const rejectLink = links.find((l) => l.action === 'reject')!;
    const result = await validateActionToken(rejectLink.token, TEST_SECRET);
    expect(result.action).toBe('reject');

    const infoLink = links.find((l) => l.action === 'request_info')!;
    const infoResult = await validateActionToken(infoLink.token, TEST_SECRET);
    expect(infoResult.action).toBe('request_info');
  });

  it('should reject a token signed with a different secret', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
    });

    const approveLink = links.find((l) => l.action === 'approve')!;

    await expect(
      validateActionToken(approveLink.token, 'wrong-secret-key-different')
    ).rejects.toThrow();
  });

  it('should reject a malformed token', async () => {
    await expect(validateActionToken('not-a-valid-jwt', TEST_SECRET)).rejects.toThrow();
  });

  it('should reject an expired token', async () => {
    // Generate a token with very short expiry
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
      expiryHours: 0, // Immediate expiry (0 hours = already expired)
    });

    const approveLink = links.find((l) => l.action === 'approve')!;

    // Wait a moment to ensure expiry
    await new Promise((resolve) => setTimeout(resolve, 1100));

    await expect(validateActionToken(approveLink.token, TEST_SECRET)).rejects.toThrow();
  });

  it('should include correct expiresAt in validated payload', async () => {
    const links = await generateActionLinks(TEST_PAYLOAD, {
      secret: TEST_SECRET,
      baseUrl: TEST_BASE_URL,
      expiryHours: 24,
    });

    const approveLink = links.find((l) => l.action === 'approve')!;
    const result = await validateActionToken(approveLink.token, TEST_SECRET);

    const expiresAt = new Date(result.expiresAt).getTime();
    const expectedApprox = Date.now() + 24 * 60 * 60 * 1000;
    // Allow 5 seconds tolerance
    expect(Math.abs(expiresAt - expectedApprox)).toBeLessThan(5000);
  });
});
